### PR TITLE
fix: correct name for self.silent_entities

### LINKED ISSUE #45: When turning on a device.
Latest skill and plugin.

```
Aug 07 15:13:31 mark2 ovos-core[8572]: 2024-08-07 15:13:31.643 - neon_homeassistant_skill.mikejgray - INFO - {'utterances': ['turn on ambiance'], 'lang': 'en-us', 'utterance': 'turn on ambiance', 'entity': 'ambiance'}
Aug 07 15:13:32 mark2 ovos-core[8572]: exception calling callback for <Future at 0x7f58472150 state=finished raised AttributeError>
Aug 07 15:13:32 mark2 ovos-core[8572]: Traceback (most recent call last):
Aug 07 15:13:32 mark2 ovos-core[8572]:   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
Aug 07 15:13:32 mark2 ovos-core[8572]:     callback(self)
Aug 07 15:13:32 mark2 ovos-core[8572]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
Aug 07 15:13:32 mark2 ovos-core[8572]:     self.emit("error", exc)
Aug 07 15:13:32 mark2 ovos-core[8572]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
Aug 07 15:13:32 mark2 ovos-core[8572]:     self._emit_handle_potential_error(event, args[0] if args else None)
Aug 07 15:13:32 mark2 ovos-core[8572]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
Aug 07 15:13:32 mark2 ovos-core[8572]:     raise error
Aug 07 15:13:32 mark2 ovos-core[8572]:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Aug 07 15:13:32 mark2 ovos-core[8572]:     result = self.fn(*self.args, **self.kwargs)
Aug 07 15:13:32 mark2 ovos-core[8572]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 07 15:13:32 mark2 ovos-core[8572]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/neon_homeassistant_skill/__init__.py", line 179, in handle_turn_on_response
Aug 07 15:13:32 mark2 ovos-core[8572]:     if device not in self.silent_devices:
Aug 07 15:13:32 mark2 ovos-core[8572]:                      ^^^^^^^^^^^^^^^^^^^
Aug 07 15:13:32 mark2 ovos-core[8572]: AttributeError: 'NeonHomeAssistantSkill' object has no attribute 'silent_devices'
```

### PR DESCRIPTION
**Pull request by mikejgray**
Closes #45

### CODE REVIEW

**Comment by mikejgray** [comment]
@goldyfruit If you'd care to test, please, this should solve your issue

**Comment by NeonDaniel** [comment]
Reviewing the diff, did you find/replace all `silent_entities` references with `silent_devices`?

I like the change to properties to handle settings changes 👍

**Comment by mikejgray** [comment]
> Reviewing the diff, did you find/replace all `silent_entities` references with `silent_devices`?
> 
> I like the change to properties to handle settings changes 👍

Other way around - it should be `silent_entities`.

I caught the properties issue when I found my tests weren't working. Love that pattern!

**Comment by goldyfruit** [comment]
All good, no more error!

```
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.683 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-cancel: {}
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.687 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-normalizer: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'en-us'}
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.688 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-corrections: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'en-us'}
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.694 - skills - ovos_core.intent_services:get_pipeline:241 - DEBUG - Session pipeline: ['stop_high', 'converse', 'padatious_high', 'ocp_high', 'adapt_high', 'ocp_medium', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'fallback_medium', 'fallback_low']
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.696 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x7f90319450>>
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.711 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x7f91c79750>>
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.713 - skills - ovos_core.intent_services.padatious_service:_match_level:48 - DEBUG - Padatious Matching confidence > 0.95
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.722 - skills - ovos_core.intent_services:handle_utterance:370 - INFO - padatious_high match: IntentMatch(intent_service='Padatious', intent_type='neon_homeassistant_skill.mikejgray:turn.on.intent', intent_data={'entity': 'plafonnier'}, skill_id='neon_homeassistant_skill.mikejgray', utterance='turn on plafonnier')
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.729 - skills - ovos_core.intent_services:handle_utterance:388 - DEBUG - intent matching took: 0.03458356857299805
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.789 - neon_homeassistant_skill.mikejgray - INFO - {'utterances': ['turn on plafonnier'], 'lang': 'en-us', 'utterance': 'turn on plafonnier', 'entity': 'plafonnier'}
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.790 - neon_homeassistant_skill.mikejgray - INFO - Trying to turn on device plafonnier
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.806 - skills - ovos_bus_client.client.client:on_default_session_update:166 - DEBUG - synced default_session
Aug 08 09:53:48 mark2 ovos-core[11595]: 2024-08-08 09:53:48.902 - neon_homeassistant_skill.mikejgray - DEBUG - Handling turn on response to {'device': 'plafonnier'}
```

Thanks @mikejgray

**Comment by goldyfruit** [comment]
When `verbose` is set to `true`, it spokes only the first sentence.

```
 turn on ambiance
 >> Sure thing.
 >> I turned on ambiance!
```

Only `Sure thing.` got a playback.

**Comment by mikejgray** [comment]
> When `verbose` is set to `true`, it spokes only the first sentence.
> 
> 
> 
> ```
> 
>  turn on ambiance
> 
>  >> Sure thing.
> 
>  >> I turned on ambiance!
> 
> ```
> 
> 
> 
> Only `Sure thing.` got a playback.

That's a separate issue, but let's diagnose a little...did the message go over the bus? Or did it just not go out at all? Could be an audio service issue or something else, or could be here

**Comment by goldyfruit** [comment]
I guess it went to the bus as its showing within the `ovos-cli-client`.

**Comment by mikejgray** [comment]
> I guess it went to the bus as its showing within the `ovos-cli-client`.

If it got sent to the bus but didn't play back I think that's an OVOS-audio problem. Any logs there to indicate why it didn't play?

**Comment by goldyfruit** [comment]
> > I guess it went to the bus as its showing within the `ovos-cli-client`.
> 
> If it got sent to the bus but didn't play back I think that's an OVOS-audio problem. Any logs there to indicate why it didn't play?

No error.

```
 turn off ambiance
 >> Okay.
 >> I turned off ambiance!
```

```
Aug 08 18:16:44 mark2 ovos-audio[17975]: 2024-08-08 18:16:44.236 - audio - ovos_audio.service:execute_tts:384 - INFO - Speak: Okay.
Aug 08 18:16:44 mark2 ovos-audio[17975]: 2024-08-08 18:16:44.249 - audio - ovos_plugin_manager.templates.tts:get_from_cache:125 - INFO - Found 2342c97172f86615a4ae27c63e4aaefc.mp3 in TTS cache
Aug 08 18:16:44 mark2 ovos-audio[19035]: /run/user/1000/tts/ovos-tts-plugin-polly/Danielle/en-us/2342c97172f86615a4ae27c63e4aaefc.mp3:
Aug 08 18:16:44 mark2 ovos-audio[19035]:  File Size: 4.22k     Bit Rate: 48.5k
Aug 08 18:16:44 mark2 ovos-audio[19035]:   Encoding: MPEG audio
Aug 08 18:16:44 mark2 ovos-audio[19035]:   Channels: 1 @ 16-bit
Aug 08 18:16:44 mark2 ovos-audio[19035]: Samplerate: 24000Hz
Aug 08 18:16:44 mark2 ovos-audio[19035]: Replaygain: off
Aug 08 18:16:44 mark2 ovos-audio[19035]:   Duration: 00:00:00.70
Aug 08 18:16:45 mark2 ovos-audio[19035]: [312B blob data]
Aug 08 18:16:45 mark2 ovos-audio[19035]: Done.

**Comment by mikejgray** [comment]
> > > I guess it went to the bus as its showing within the `ovos-cli-client`.
> > 
> > 
> > If it got sent to the bus but didn't play back I think that's an OVOS-audio problem. Any logs there to indicate why it didn't play?
> 
> No error.
> 
> ```
>  turn off ambiance
>  >> Okay.
>  >> I turned off ambiance!
> ```
> 
> ```
> Aug 08 18:16:44 mark2 ovos-audio[17975]: 2024-08-08 18:16:44.236 - audio - ovos_audio.service:execute_tts:384 - INFO - Speak: Okay.
> Aug 08 18:16:44 mark2 ovos-audio[17975]: 2024-08-08 18:16:44.249 - audio - ovos_plugin_manager.templates.tts:get_from_cache:125 - INFO - Found 2342c97172f86615a4ae27c63e4aaefc.mp3 in TTS cache
> Aug 08 18:16:44 mark2 ovos-audio[19035]: /run/user/1000/tts/ovos-tts-plugin-polly/Danielle/en-us/2342c97172f86615a4ae27c63e4aaefc.mp3:
> Aug 08 18:16:44 mark2 ovos-audio[19035]:  File Size: 4.22k     Bit Rate: 48.5k
> Aug 08 18:16:44 mark2 ovos-audio[19035]:   Encoding: MPEG audio
> Aug 08 18:16:44 mark2 ovos-audio[19035]:   Channels: 1 @ 16-bit
> Aug 08 18:16:44 mark2 ovos-audio[19035]: Samplerate: 24000Hz
> Aug 08 18:16:44 mark2 ovos-audio[19035]: Replaygain: off
> Aug 08 18:16:44 mark2 ovos-audio[19035]:   Duration: 00:00:00.70
> Aug 08 18:16:45 mark2 ovos-audio[19035]: [312B blob data]
> Aug 08 18:16:45 mark2 ovos-audio[19035]: Done.
> ```

Interestingly, I only get the second message spoken...

**Comment by mikejgray** [comment]
Okay, when I add `"verbose": true` to my settings.json file, I get both replies. I only get the second otherwise. Have you set any `silent_devices` in your skill settings? That would cause the second reply not to be spoken.

**Comment by goldyfruit** [comment]
> silent_devices

Nop, here is my `settings.json`
```json
{
  "disable_intents": false,
  "__mycroft_skill_firstrun": false,
  "verbose": true
}
```

**Comment by mikejgray** [comment]
> > silent_devices
> 
> Nop, here is my `settings.json`
> 
> ```json
> {
>   "disable_intents": false,
>   "__mycroft_skill_firstrun": false,
>   "verbose": true
> }
> ```

Is this new behavior since this patch?

**Pull request merged**
